### ISSUE TITLE
Add installation instructions to README.md

### ISSUE THREAD

**Issue by myhau** [felixSchl/git-fiddle#1]

**Comment by tdeekens** [comment]
Maybe we can provide a PR with a formula for homebrew?

**Comment by felixSchl** [comment]
Problem is I have not thought about how to install it yet myself. Ideally it would register itself as a git alias, so you could do `git fiddle [args...]`. Homebrew sounds awesome, but be aware that this is still alpha quality software, I literally hacked it together this weekend. I'd like to be able to use it with zplug, for personal use.

**Comment by rudis** [comment]
Name it `git-fiddle`, put it somewhere in your `$PATH` and git will pick it up and allow using it with `git fiddle`.

**Comment by felixSchl** [comment]
@rudis this is pretty cool. I've also moved the man-page, so if the git-fiddle project directory is in `$MANPATH`, `git fiddle --help` will open the man page.
