### ISSUE TITLE
git fiddle windows support

### ISSUE THREAD

**Issue by pibi** [felixSchl/git-fiddle#7]
Thanks a lot for this plugin.
I wasn't able to use it on Windows due to this error (Git for Windows v2.7.0, windows7, docker shell):

```
/mingw64/libexec/git-core/git-rebase--interactive: line 255: C:/Program: No such
 file or directory
Could not execute editor
```

I fixed it by adding a '' on GIT_SEQUENCE_EDITOR line 112:

`GIT_SEQUENCE_EDITOR="'${SCRIPT_DIR}/_fiddle_seq_editor'" \`

Not sure if it is cross compatible, so I'm just leaving this here hoping it will be useful.

**Comment by felixSchl** [comment]
Thanks! I'll set up testing on appveyor and commit your fix if it still runs on the other platforms, unless you want to submit a PR.
